branches:
  only:
    - master

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.11,<1.12"
  - DJANGO_VERSION=">=2.0,<2.1"

matrix:
  exclude:
    # django 2 doesn't support python 2
    - python: '2.7'
      env: DJANGO_VERSION=">=2.0,<2.1"

install:
  # install setup.py's dependencies, dev requirements, and django
  - pip install -e . -r requirements-dev.txt django$DJANGO_VERSION

script:
  - python manage.py test
  - pyflakes eventhandler

sudo: false

cache: pip
